namespace SpriteKind {
    export const hitbox = SpriteKind.create()
}
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    damaage()
})
function damaage () {
    if (game.runtime() - time_stamp >= 600 && controller.left.isPressed()) {
        animation.runImageAnimation(
        mySprite,
        assets.animation`bull`,
        100,
        false
        )
        pellets_1 = sprites.create(img`
            . . c . . . 
            . . . . . . 
            . . . . c . 
            c . . c . c 
            . . c . . . 
            . . . . . c 
            c . . . . . 
            . . c . . c 
            . . . c . . 
            `, SpriteKind.Projectile)
        pellets_2 = sprites.create(img`
            c . . . . 
            c . c . c 
            . c c . c 
            . c . . . 
            c . c . . 
            . c c . . 
            c c . . . 
            . c . . . 
            c . . . . 
            `, SpriteKind.Projectile)
    }
    if (game.runtime() - time_stamp >= 600 && controller.right.isPressed()) {
        animation.runImageAnimation(
        mySprite,
        [img`
            ........................
            .......fffff............
            .......fffff............
            .......fccc.............
            .......dddc.............
            .......dddd.............
            ........dd..............
            .......f111.............
            .......ff11bbb..........
            .......f1fffd...........
            .......f111.............
            .......f111.............
            .......f111.............
            .......ffff.............
            .......8888888..........
            .......8888888..........
            .......88...88..........
            ...ff8888...88..........
            ...ff8888...fff.........
            ...ff.......fff.........
            `,img`
            ........................
            .......fffff............
            .......fffff............
            .......fccc.............
            .......dddc.............
            .......dddd.......c.c...
            ........dd..........c...
            .......f111.............
            .......ff11bbb...c.c....
            .......f1fffd...........
            .......f111..........c..
            .......f111.......c.....
            .......f111.........c...
            .......ffff.............
            .......8888888..........
            .......8888888..........
            .......88...88..........
            ...ff8888...88..........
            ...ff8888...fff.........
            ...ff.......fff.........
            `,img`
            ........................
            .......fffff............
            .......fffff............
            .......fccc.........c..c
            .......dddc...........c.
            .......dddd.............
            ........dd..........c...
            .......f111.............
            .......ff11bbb.....cc.c.
            .......f1fffd........c..
            .......f111...........c.
            .......f111............c
            .......f111.............
            .......ffff.............
            .......8888888..........
            .......8888888..........
            .......88...88..........
            ...ff8888...88..........
            ...ff8888...fff.........
            ...ff.......fff.........
            `],
        500,
        false
        )
        pellets_1 = sprites.create(img`
            . . c . . . 
            . . . . . . 
            . . . . c . 
            c . . c . c 
            . . c . . . 
            . . . . . c 
            c . . . . . 
            . . c . . c 
            . . . c . . 
            `, SpriteKind.Projectile)
        pellets_2 = sprites.create(img`
            c . . . . 
            c . c . c 
            . c c . c 
            . c . . . 
            c . c . . 
            . c c . . 
            c c . . . 
            . c . . . 
            c . . . . 
            `, SpriteKind.Projectile)
    }
    if (game.runtime() - time_stamp >= 600 && controller.up.isPressed()) {
        animation.runImageAnimation(
        mySprite,
        [img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `],
        500,
        false
        )
        pellets_1 = sprites.create(img`
            . . c . . . 
            . . . . . . 
            . . . . c . 
            c . . c . c 
            . . c . . . 
            . . . . . c 
            c . . . . . 
            . . c . . c 
            . . . c . . 
            `, SpriteKind.Projectile)
        pellets_2 = sprites.create(img`
            c . . . . 
            c . c . c 
            . c c . c 
            . c . . . 
            c . c . . 
            . c c . . 
            c c . . . 
            . c . . . 
            c . . . . 
            `, SpriteKind.Projectile)
    }
    if (game.runtime() - time_stamp >= 600 && controller.down.isPressed()) {
        animation.runImageAnimation(
        mySprite,
        [img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `],
        500,
        false
        )
        pellets_1 = sprites.create(img`
            . . c . . . 
            . . . . . . 
            . . . . c . 
            c . . c . c 
            . . c . . . 
            . . . . . c 
            c . . . . . 
            . . c . . c 
            . . . c . . 
            `, SpriteKind.Projectile)
        pellets_2 = sprites.create(img`
            c . . . . 
            c . c . c 
            . c c . c 
            . c . . . 
            c . c . . 
            . c c . . 
            c c . . . 
            . c . . . 
            c . . . . 
            `, SpriteKind.Projectile)
    }
}
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    mySprite,
    [img`
        ....................
        .....fffff..........
        .....fffff..........
        ......cccf..........
        ......cddd..........
        ......dddd..........
        .......dd...........
        ......111f..........
        ..bbbbbeef..........
        ...deedfff..........
        ......e1ef..........
        ......111f..........
        ......111f..........
        ......ffff..........
        ...8888888..........
        ...8888888..........
        ...88...88..........
        ...88...8888ff......
        ..fff...8888ff......
        ..fff.......ff......
        `],
    500,
    false
    )
})
sprites.onCreated(SpriteKind.hitbox, function (sprite) {
    let myEnemy: Sprite = null
    sprite.setPosition(mySprite.x + 7, mySprite.y + 7)
    pause(500)
    sprites.destroy(mySprite3)
    sprites.destroy(myEnemy)
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    mySprite,
    [img`
        ....................
        .........fffff......
        .........fffff......
        .........fccc.......
        .........dddc.......
        .........dddd.......
        ..........dd........
        .........f111.......
        .........ff11bbb....
        .........f1fffd.....
        .........f111.......
        .........f111.......
        .........f111.......
        .........ffff.......
        .........8888888....
        .........8888888....
        .........88...88....
        .....ff8888...88....
        .....ff8888...fff...
        .....ff.......fff...
        `],
    500,
    false
    )
})
let pellets_2: Sprite = null
let pellets_1: Sprite = null
let mySprite: Sprite = null
let mySprite3: Sprite = null
let time_stamp = 0
time_stamp = game.runtime()
tiles.setCurrentTilemap(tilemap`level`)
mySprite3 = sprites.create(img`
    ............................................................
    ............................................................
    ............................................................
    ............................................................
    ...................c........................................
    ...................c........................................
    ...................c........................................
    ...................c........................................
    ...................c........................................
    ...................c........................................
    ...................c.ccccc..................................
    ...................cccaaaccc................................
    ...................c22aaa22c................................
    ...................ca22222ac................................
    ...................ccaa2aacc................................
    ....................caaaaac.................................
    ......ccc...c...cc..ccaaacc..cc...c...ccc...................
    ......cacccccaaaacc.accacca.ccaaaacccccac...................
    ......caaaaccaaaaaccaacccaaccaaaaaccaaaac...................
    ......caaaaccaaaaaacc..a..ccaaaaaaccaaaac...................
    ......caaaaccaaaaaaacccccccaaaaaaaccaaaac...................
    ......caaaaccaaaaaaaaaaaaaaaaaaaaaccaaaac...................
    ......caaaac.ccaaaaaaaaaaaaaaaaacc.caaaac...................
    ......caaaac..caaaaaaaaaaaaaaaaac..caaaac...................
    ......caaaac..caaaaaaaaaaaaaaaaac..caaaac...................
    ......caaaac..caaaaaaaaaaaaaaaaac..caaaac...................
    .......aaaac..caaaaaaaaaaaaaaaaac..caaaa....................
    .......aaac....caaaaaaaaaaaaaaac....caaa....................
    .......aaca....ccccaaaaaaaaacccc....acaa....................
    .......acaa.....caccccaaaccccac.....aaca....................
    .......caaa.....caaaacccccaaaac.....aaac....................
    .......aaaa.....caaaaaaaaaaaaac.....aaaa....................
    .......aaaa.....caaaaaaaaaaaaac.....aaaa....................
    .......aaaa.....ccaaaacccaaaacc.....aaaa....................
    ......aaccca.....acaacaaaaaaca.....acccaa...................
    ......ccaaaa.cccccaccaacaaccaccccc.aaaacc...................
    ......aaaaaa.cccccaaaaaaacaaaccccc.aaaaaa...................
    ......aaaaaa.cccccccaacccaaccccccc.aaaaaa...................
    ......aaaaaa.cccccccccaaaccccccccc.aaaaaa...................
    ......aaaaaa...ccccccccccccccccc............................
    ...............aaacccccccccccaaa............................
    ...............aaaaacccccccaaaaa............................
    ..............aaaaaaacccccaaaaaaa...........................
    ..............aaaaaaacccccaaaaaaa...........................
    ..............aaaaaaa.....aaaaaaa...........................
    ..............aaaaaaa.....aaaaaaa...........................
    ...............aaaaa.......aaaaa............................
    ..............aaaaaa.......aaaaaa...........................
    .............aaaaaaa.......aaaaaaa..........................
    .............aaaaccc.......cccaaaa..........................
    .............aaaaccc.......cccaaaa..........................
    .............aaaaccc.......cccaaaa..........................
    .............aaaaccc.......cccaaaa..........................
    ...........cccccccccc.....cccccccccc........................
    ...........cccccccccc.....cccccccccc........................
    ...........cccccccccc.....cccccccccc........................
    ............................................................
    ............................................................
    ............................................................
    ............................................................
    `, SpriteKind.Enemy)
mySprite3.follow(mySprite)
mySprite = sprites.create(assets.image`myImage2`, SpriteKind.Player)
controller.moveSprite(mySprite, 100, 100)
tiles.placeOnTile(mySprite, tiles.getTileLocation(50, 58))
scene.cameraFollowSprite(mySprite)
